# Generated by Django 5.0.6 on 2026-08-12 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "schedule_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable schedule, e.g. cron expression '*/15 * * * *'",
                        max_length=255,
                    ),
                ),
                (
                    "expected_interval_seconds",
                    models.PositiveIntegerField(
                        help_text="How often this job should send a heartbeat, in seconds."
                    ),
                ),
                (
                    "grace_period_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Extra time allowed past the expected interval before alerting.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_heartbeat_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("healthy", "Healthy"),
                            ("late", "Late"),
                            ("failed", "Failed"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Heartbeat",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heartbeats",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "-received_at"],
                        name="jobs_heartb_job_id_78082a_idx",
                    )
                ],
            },
        ),
    ]
